# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rZOGZxgJuYjLB4F5y9jpNEWB-561mpH
"""


# ==============================
# Setup Colab Environment
# ==============================

# Uninstall conflicting packages
!pip uninstall -y tensorflow-decision-forests tensorflow-text tf-keras opencv-python opencv-python-headless opencv-contrib-python ydf

# Install required packages with fixed versions
!pip install tensorflow==2.17.0
!pip install tensorflow-hub
!pip install tensorflow-datasets
!pip install numpy==1.26.4
!pip install protobuf==4.25.8
!pip install -U ml_dtypes
!pip install pubchempy
!pip install git+https://github.com/tensorflow/addons.git

# ==============================
# Mount Google Drive
# ==============================
from google.colab import drive
drive.mount('/content/drive')

# ==============================
# Imports and Utilities
# ==============================
import os
import random
import math
import numpy as np
import pandas as pd
import networkx as nx
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow_addons as tfa
from tqdm import tqdm
from zipfile import ZipFile
from urllib.request import urlretrieve
from pubchempy import *

print("✅ Setup completed successfully.")
